# Generated by Django 4.2.1 on 2023-09-04 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DollarSign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='purchase_date',
            field=models.DateField(default=datetime.date(2023, 9, 1)),
        ),
        migrations.AddField(
            model_name='stock',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
