# Generated by Django 4.2.1 on 2023-09-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DollarSign', '0002_stock_purchase_date_stock_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
