# Generated by Django 4.2.1 on 2023-09-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DollarSign', '0003_alter_stock_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='companyName',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='stock',
            name='symbol',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
