# Generated by Django 4.2.1 on 2023-09-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DollarSign', '0006_alter_stock_marketcap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='ytdChange',
        ),
        migrations.AddField(
            model_name='stock',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='returnYTD',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='marketCap',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='peRatio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='previousClose',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='week52High',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='week52Low',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
